server:
  port: 8080

spring:
  application:
    name: sim-netty-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sim?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.sy.im.common.model
  configuration:
    map-underscore-to-camel-case: true

im:
  server:
    port: 9000

